[workspace]
members = ["crates/*"]

[package]
name = "itermore"
version = "0.2.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "More iterator adaptors."
repository = "https://github.com/rossmacarthur/itermore"
license = "MIT OR Apache-2.0"
keywords = ["iterator", "chunks", "windows"]
categories = ["algorithms", "rust-patterns"]

[dependencies]
iterchunks = { version = "0.1.0", path = "crates/chunks", optional = true }
iterwindows = { version = "0.1.0", path = "crates/windows", optional = true }

[features]
default = ["std", "chunks", "windows"]

std = []

chunks = ["dep:iterchunks"]
windows = ["dep:iterwindows"]
