[workspace]
members = ["crates/*"]

[package]
name = "itermore"
version = "0.4.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
rust-version = "1.56"
description = "🤸‍♀️ More iterator adaptors"
repository = "https://github.com/rossmacarthur/itermore"
license = "MIT OR Apache-2.0"
keywords = ["iterator", "chunks", "windows"]
categories = ["algorithms", "rust-patterns"]

[dependencies]
arrays = { version = "0.1.0", path = "crates/arrays", optional = true }
iterchunks = { version = "0.2.0", path = "crates/chunks", optional = true }
iterwindows = { version = "0.2.0", path = "crates/windows", optional = true }

[features]
default = ["std", "chunks", "combinations", "sorted", "windows"]

std = ["alloc"]
alloc = []

chunks = ["dep:iterchunks"]
combinations = ["dep:arrays"]
sorted = []
windows = ["dep:iterwindows"]
